name: Lint Code Base

on:
    push:
        branches-ignore: main # Ignore push events for main branches
    pull_request:
        branches: main # Run on pull requests targeting main branches

jobs:
    lint:
        name: Lint Code Base
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: read
            statuses: write

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0 # Fetch full git history for proper file change detection

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9.16

            - name: Install Python Dependencies
              run: |
                  pip install -r requirements.txt
                  pip install pylint black flake8

            - name: Lint Python
              run: |
                  pylint **/*.py --disable=R0801
                  flake8 **/*.py
                  black --check **/*.py

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16

            # - name: Install JavaScript Dependencies
            #   run: |
            #       npm i

            # - name: Lint JavaScript and TypeScript
            #   run: |
            #       npm run lint

            - name: Install YAML Dependencies
              run: |
                  npm install -g yaml-lint

            - name: Lint YAML
              run: |
                  yamllint **/*.yml

            - name: Install Markdown Dependencies
              run: |
                  npm install -g markdownlint-cli

            - name: Lint Markdown
              run: |
                  markdownlint **/*.md --ignore node_modules --ignore .github --config .markdownlint.jsonc
